### ISSUE TITLE
重写NSMutableArray的方法无效

### ISSUE THREAD

**Issue by johntaiii** [demonnico/JSPatchSDKPod#2]
能帮忙看下有什么问题吗？

```
defineClass("NSMutableArray",{
addObject:function(anObject){
        if(anObject != null){
            self.ORIGAddObject(anObject)
        }},
        })
```

**Comment by demonnico** [comment]
你好
@johntaiii 不用JSPatch的话应该也没法method swizzling `addObject`吧，建议看一下类簇方便的知识，http://stackoverflow.com/questions/23710197/is-it-possible-to-swizzle-addobject-in-nsmutablearray
